FROM ghcr.io/prefix-dev/pixi:0.47.0

# Install binchicken and dependencies
RUN mkdir /app
COPY pixi.toml /app
WORKDIR /app

SHELL ["/bin/bash", "--login", "-c"]
RUN pixi install
RUN pixi global install git
RUN pixi global install wget

# Download some example data so we can test the installation
RUN git clone https://github.com/AroneyS/binchicken bc && \
    cd bc && \
    git checkout vBINCHICKEN_VERSION && \
    cd ..

# Build the subprocess environments
RUN pixi run \
    binchicken build \
    --checkm2-db /binchicken/CheckM2_database \
    --singlem-metapackage /binchicken/singlem_metapackage \
    --download-databases

# Run coassemble
RUN pixi run \
    binchicken coassemble \
    --forward bc/test/data/sample_1.1.fq bc/test/data/sample_2.1.fq bc/test/data/sample_3.1.fq \
    --reverse bc/test/data/sample_1.2.fq bc/test/data/sample_2.2.fq bc/test/data/sample_3.2.fq \
    --genomes bc/test/data/GB_GCA_013286235.1.fna \
    --assemble-unmapped --unmapping-max-identity 99 --unmapping-max-alignment 90 \
    --prodigal-meta --output test_pixi

RUN cat test_pixi/coassemble/target/elusive_clusters.tsv
